### ISSUE TITLE
xunit task passes multiple assemblies to xunit.console.exe

### ISSUE THREAD

**Issue by jtdowney** [mxriverlynn/Albacore#47]
The xunit.console.exe runner does not accept multiple assemblies (unlike nunit.console.exe) as parameters and is meant to be called multiple times with each new assembly to test.

**Comment by mxriverlynn** [comment]
thanks for bringing this to my attention. the xunit code had been copied from the nunit code, without really checking to see what the full differences were. i've corrected the API for xunit so that it only accepts one assembly, now:

<code>xunit.assemlby = "mytests.dll"</code>

this is currently in the dev branch, and will be released in the 0.1.0 version, hopefully in less than a week.
